again rework support scripts for big db imports

diff --git a/scripts/generate-initial-graph b/scripts/generate-initial-graph
--- a/scripts/generate-initial-graph
+++ b/scripts/generate-initial-graph
@@ -1,8 +1,15 @@
+#!/bin/bash
 
-rm -rf tlpdb/2018-10-07/out
-./tl-dump-neo4j --initial --date="2018-10-07" --output=tlpdb/2018-10-07/out tlpdb/2018-10-07/texlive.tlpdb
+first="$1"
+if [ ! -r "$first/texlive.tlpdb" ] ; then
+  echo "Cannot read $first/texlive.tlpdb" >&2
+  exit 1
+fi
+dtstr=$(echo $first | cut -b 7-)
+rm -rf "$first/out"
+./tl-dump-neo4j --initial --date="$dtstr" --output="$first/out" "$first/texlive.tlpdb"
 
-cd tlpdb/2018-10-07/out
+cd "$first/out"
 
 cmdline=
 for x in node-*.csv ; do
diff --git a/scripts/update-graph b/scripts/update-graph
--- a/scripts/update-graph
+++ b/scripts/update-graph
@@ -1,3 +1,4 @@
+#!/bin/bash
 
 if [ -z "$NEO4J_USERNAME" ] ; then
   echo "need NEO4J_USERNAME environment variable, exiting!" >&2
@@ -7,13 +8,14 @@ if [ -z "$NEO4J_PASSWORD" ] ; then
   echo "need NEO4J_PASSWORD environment variable, exiting!" >&2
   exit 1
 fi
-for i in 08 09 10 11 12 13 14 15 ; do
-  if [ ! -r tlpdb/2018-10-$i/cypher-import-statement ] ; then
-    echo "not found: tlpdb/2018-10-$i/cypher-import-statement, exiting!" >&2
+todos=$(ls -d tlpdb/20* | tail -n +2)
+for todo in $todos ; do
+  if [ ! -r $todo/cypher-import-statement ] ; then
+    echo "not found: $todo/cypher-import-statement, exiting!" >&2
     exit 1
   fi
-  echo "Running cypher statements tlpdb/2018-10-$i/cypher-import-statement"
-  cat tlpdb/2018-10-$i/cypher-import-statement | cypher-shell
+  echo "Running cypher statements $todo/cypher-import-statement"
+  cat $todo/cypher-import-statement | cypher-shell
 done
 
 
